#!/usr/bin/env bash

# Default editor
export EDITOR="vi";

# Default less settings
export LESS="-FRX"

# Remove some commands from history
export HISTIGNORE="ls:l:la:cd*:pwd:exit:date:* --help";
export HISTCONTROL=ignoredups;

# Print date and time with history
export HISTTIMEFORMAT="%h %d %H:%M:%S > ";

# Make sure brew works nicely with nvm
source $(brew --prefix nvm)/nvm.sh

# Path for nvm
export NVM_DIR=~/.nvm

# Export command prompt
export PS1="[\t]:\[\033[1;97m\]\W ❯\[\033[0m\] ";

# Export caskroom location
export HOMEBREW_CASK_OPTS="--caskroom=$(brew --repository)/Caskroom";

