#!/usr/bin/env bash

# Add android SDK to path
export PATH=$PATH:/Users/t.vandam/Library/Application\ Support/Fusetools/Fuse/Android/AndroidSDK/platform-tools;

# Add casks to path
export PATH=$PATH:$(brew --repository)/Caskroom;

# Add cabal binaries to path
export PATH=$PATH:~/.cabal/bin;

